Dataset disponible sur https://www.kaggle.com/datasets/huanghanchina/pascal-voc-2012?resource=download

Pour tester quelques images (attention c'est un gros dataset -W 27Go): https://www.kaggle.com/datasets/awsaf49/coco-2017-dataset

In [1]:
import tensorflow as tf
import numpy as np
import xml.etree.ElementTree as ET
import os
import shutil
import cv2
import albumentations as A
from tensorflow.keras.layers import (Conv2D, Dense, Flatten, BatchNormalization, Dropout, Reshape, LeakyReLU)
from tensorflow.keras.optimizers import Adam

## Data Preparation

In [2]:
train_images = 'VOC2012/JPEGImages/'
train_maps = 'VOC2012/Annotations/'

val_images = 'VOC2012/ValJPEGImages/'
val_maps = 'VOC2012/ValAnnotations/'

classes = ['aeroplane','bicycle','bird','boat','bottle','bus','car','cat','chair','cow','diningtable', 'dog','horse','motorbike','person','pottedplant','sheep','sofa','train','tvmonitor']

B = 2
N_CLASSES = len(classes)
H,W = 224,224
SPLIT_SIZE = H // 32
print(SPLIT_SIZE)
N_EPOCHS = 135
BATCH_SIZE = 32

7


In [3]:
val_list = ['2007_000027.jpg','2007_000032.jpg','2007_000033.jpg','2007_000039.jpg','2007_000042.jpg','2007_000061.jpg',
            '2007_000063.jpg','2007_000068.jpg','2007_000121.jpg','2007_000123.jpg','2007_000129.jpg','2007_000170.jpg',
            '2007_000175.jpg','2007_000187.jpg','2007_000241.jpg','2007_000243.jpg','2007_000250.jpg','2007_000256.jpg',
            '2007_000272.jpg','2007_000323.jpg','2007_000332.jpg','2007_000333.jpg','2007_000346.jpg','2007_000363.jpg',
            '2007_000364.jpg','2007_000392.jpg','2007_000423.jpg','2007_000452.jpg','2007_000464.jpg','2007_000480.jpg',
            '2007_000491.jpg','2007_000504.jpg','2007_000515.jpg','2007_000528.jpg','2007_000529.jpg','2007_000549.jpg',
            '2007_000559.jpg','2007_000572.jpg','2007_000584.jpg','2007_000629.jpg','2007_000636.jpg','2007_000645.jpg',
            '2007_000648.jpg','2007_000661.jpg','2007_000663.jpg','2007_000664.jpg','2007_000676.jpg','2007_000713.jpg',
            '2007_000720.jpg','2007_000727.jpg','2007_000733.jpg','2007_000738.jpg','2007_000762.jpg','2007_000768.jpg',
            '2007_000783.jpg','2007_000793.jpg','2007_000799.jpg','2007_000804.jpg','2007_000807.jpg','2007_000822.jpg',
            '2007_001299.jpg','2007_001311.jpg','2007_001321.jpg','2007_001340.jpg']

In [4]:
# for name in val_list:
#     shutil.move(train_maps+name[:-3]+"xml", val_maps+name[:-3]+"xml")

In [5]:
# for name in val_list:
#     shutil.move(train_images+name, val_images+name)

In [6]:
def preprocess_xml(filename):
    tree = ET.parse(filename)
    root = tree.getroot()
    size_tree = root.find('size')
    height = float(size_tree.find('height').text)
    width = float(size_tree.find('width').text)
    bounding_boxes = []
    
    for object_tree in root.findall('object'):
        for bounding_box in object_tree.iter('bndbox'):
            xmin = (float(bounding_box.find('xmin').text))
            ymin = (float(bounding_box.find('ymin').text))
            xmax = (float(bounding_box.find('xmax').text))
            ymax = (float(bounding_box.find('ymax').text))
            # print(xmin, ymin, xmax, ymax)
            break
        
        class_name = object_tree.find('name').text
        class_dict = {classes[i]:i for i in range(len(classes))}
        bounding_box = [
            (xmin+xmax)/(2*width), (ymin+ymax)/(2*height), (xmax-xmin)/width,
            (ymax-ymin)/height, class_dict[class_name]]
        bounding_boxes.append(bounding_box)
    
    return tf.convert_to_tensor(bounding_boxes)

In [7]:
preprocess_xml(val_maps + "2007_000032.xml")

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[ 0.479     ,  0.4644128 ,  0.542     ,  0.37366548,  0.        ],
       [ 0.33      ,  0.37544483,  0.128     ,  0.12455516,  0.        ],
       [ 0.408     ,  0.727758  ,  0.036     ,  0.17437722, 14.        ],
       [ 0.07      ,  0.7597865 ,  0.036     ,  0.17437722, 14.        ]],
      dtype=float32)>

In [8]:
def generate_output(bounding_boxes):
    output_label=np.zeros((SPLIT_SIZE,SPLIT_SIZE,N_CLASSES+5))
    for b in range(len(bounding_boxes)):
        grid_x = bounding_boxes[..., b, 0] * SPLIT_SIZE
        grid_y = bounding_boxes[..., b, 1] * SPLIT_SIZE
        i = int(grid_x)
        j = int(grid_y)

        output_label[i, j, 0:5] = [1., grid_x%1, grid_y%1, bounding_boxes[...,b,2], bounding_boxes[...,b,3]]
        output_label[i, j, 5+int(bounding_boxes[..., b, 4])] = 1.

    return tf.convert_to_tensor(output_label,tf.float32)

In [9]:
generate_output(preprocess_xml(val_maps+"2007_000032.xml"))[3][3]

<tf.Tensor: shape=(25,), dtype=float32, numpy=
array([1.        , 0.35299993, 0.25088978, 0.542     , 0.37366548,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ],
      dtype=float32)>

In [10]:
im_paths = []
xml_paths = []

val_im_paths = []
val_xml_paths = []

for i in os.listdir(train_maps):
    im_paths.append(train_images+i[:-3]+'jpg')
    xml_paths.append(train_maps+i)

for i in os.listdir(val_maps):
    val_im_paths.append(val_images+i[:-3]+'jpg')
    val_xml_paths.append(val_maps+i)

print(len(im_paths), len(xml_paths))
print(len(val_im_paths), len(val_xml_paths))

17061 17061
64 64


In [11]:
train_dataset = tf.data.Dataset.from_tensor_slices((im_paths, xml_paths))
val_dataset = tf.data.Dataset.from_tensor_slices((val_im_paths, val_xml_paths))

In [12]:
for i in val_dataset.take(1):
    print(i)

(<tf.Tensor: shape=(), dtype=string, numpy=b'VOC2012/ValJPEGImages/2007_000027.jpg'>, <tf.Tensor: shape=(), dtype=string, numpy=b'VOC2012/ValAnnotations/2007_000027.xml'>)


In [13]:
def get_imbboxes(im_path, xml_path):
    img = tf.io.decode_jpeg(tf.io.read_file(im_path))
    img = tf.cast(tf.image.resize(img, size=[H, W]), dtype=tf.float32)

    bboxes = tf.numpy_function(func=preprocess_xml, inp=[xml_path], Tout=tf.float32)
    return img, bboxes

In [14]:
train_dataset = train_dataset.map(get_imbboxes)
val_dataset = val_dataset.map(get_imbboxes)

In [15]:
for i, j in train_dataset.skip(2):
    print(i.shape, j)
    break

(224, 224, 3) tf.Tensor([[0.626      0.40727273 0.208      0.34181818 3.        ]], shape=(1, 5), dtype=float32)


In [16]:
cv2.imwrite('out_1.jpg', np.array(i))

True

In [17]:
transforms = A.Compose([
    A.Resize(H, W),
    A.RandomCrop(width=np.random.randint(int(0.9 * W), 224), height=np.random.randint(int(0.9 * H), 224), p=0.5),
    A.RandomScale(scale_limit=0.1, interpolation=cv2.INTER_LANCZOS4, p=0.5),
    A.HorizontalFlip(p=0.5),
    A.Resize(H, W)
], bbox_params=A.BboxParams(format='yolo', min_area=25, min_visibility=0.1))

In [18]:
def aug_albument(image, bboxes):
    augmented = transforms(image=image, bboxes=bboxes)
    return [tf.convert_to_tensor(augmented["image"], dtype=tf.float32), tf.convert_to_tensor(augmented["bboxes"], dtype=tf.float32)]

In [19]:
def process_data(image, bboxes):
    aug = tf.numpy_function(func=aug_albument, inp=[image, bboxes], Tout=(tf.float32, tf.float32))
    return aug[0], aug[1]

In [20]:
train_dataset = train_dataset.map(process_data)

In [21]:
for i, j in train_dataset.skip(2):
    print(i.shape, j)
    break

(224, 224, 3) tf.Tensor([[0.62488073 0.43315092 0.21372478 0.3716858  3.        ]], shape=(1, 5), dtype=float32)


In [22]:
cv2.imwrite('out_2.jpg', np.array(i))

True

In [23]:
def preprocess_augment(img, y):
    img = tf.image.random_brightness(img, max_delta=50.)
    img = tf.image.random_saturation(img, lower=0.5, upper=1.5)
    img = tf.image.random_contrast(img, lower=0.5, upper=1.5)
    # img = tf.image.random_hue(img, max_delta=0.5)
    img = tf.clip_by_value(img, 0, 255)
    labels = tf.numpy_function(func=generate_output, inp=[y], Tout=(tf.float32))
    return img, labels

In [24]:
def preprocess(img, bboxes):
    img = tf.cast(tf.image.resize(img, size=[H, W]), dtype=tf.float32)

    labels = tf.numpy_function(func=generate_output, inp=[bboxes], Tout=(tf.float32))
    return img, labels

In [25]:
train_dataset = train_dataset.map(preprocess_augment)
val_dataset = val_dataset.map(preprocess)

In [26]:
train_dataset = (
    train_dataset
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

In [27]:
val_dataset = (
    val_dataset
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

In [28]:
for i, j in train_dataset.take(1):
    print(i.shape, j)
    break

(32, 224, 224, 3) tf.Tensor(
[[[[0.         0.         0.         ... 0.         0.
    0.        ]
   [0.         0.         0.         ... 0.         0.
    0.        ]
   [0.         0.         0.         ... 0.         0.
    0.        ]
   ...
   [0.         0.         0.         ... 0.         0.
    0.        ]
   [0.         0.         0.         ... 0.         0.
    0.        ]
   [0.         0.         0.         ... 0.         0.
    0.        ]]

  [[0.         0.         0.         ... 0.         0.
    0.        ]
   [0.         0.         0.         ... 0.         0.
    0.        ]
   [0.         0.         0.         ... 0.         0.
    0.        ]
   ...
   [0.         0.         0.         ... 0.         0.
    0.        ]
   [0.         0.         0.         ... 0.         0.
    0.        ]
   [0.         0.         0.         ... 0.         0.
    0.        ]]

  [[0.         0.         0.         ... 0.         0.
    0.        ]
   [0.         0.         0.  

In [29]:
cv2.imwrite('out_3.jpg', np.array(i[2]))

True

## Model

In [30]:
NUM_FILTERS = 512
OUTPUT_DIM = N_CLASSES + 5 * B

In [31]:
# base_model = tf.keras.applications.resnet50.ResNet50(
base_model = tf.keras.applications.efficientnet.EfficientNetB1(
    weights = 'imagenet',
    input_shape = (H, W, 3),
    include_top = False
)
base_model.trainable = False

In [32]:
model = tf.keras.Sequential([
    base_model,
    Conv2D(NUM_FILTERS, (3, 3), padding = 'same', kernel_initializer = 'he_normal'),
    BatchNormalization(),
    LeakyReLU(alpha=0.1),

    Conv2D(NUM_FILTERS, (3, 3), padding = 'same', kernel_initializer = 'he_normal'),
    BatchNormalization(),
    LeakyReLU(alpha=0.1),

    Conv2D(NUM_FILTERS, (3, 3), padding = 'same', kernel_initializer = 'he_normal'),
    BatchNormalization(),
    LeakyReLU(alpha=0.1),

    Conv2D(NUM_FILTERS, (3, 3), padding = 'same', kernel_initializer = 'he_normal'),
    LeakyReLU(alpha=0.1),

    Flatten(),

    Dense(NUM_FILTERS, kernel_initializer='he_normal'),
    BatchNormalization(),
    LeakyReLU(alpha=0.1),

    Dropout(0.5),

    Dense(SPLIT_SIZE * SPLIT_SIZE * OUTPUT_DIM, activation = 'sigmoid'),

    Reshape((SPLIT_SIZE, SPLIT_SIZE, OUTPUT_DIM))
])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 efficientnetb1 (Functional)  (None, 7, 7, 1280)       6575239   
                                                                 
 conv2d (Conv2D)             (None, 7, 7, 512)         5898752   
                                                                 
 batch_normalization (BatchN  (None, 7, 7, 512)        2048      
 ormalization)                                                   
                                                                 
 leaky_re_lu (LeakyReLU)     (None, 7, 7, 512)         0         
                                                                 
 conv2d_1 (Conv2D)           (None, 7, 7, 512)         2359808   
                                                                 
 batch_normalization_1 (Batc  (None, 7, 7, 512)        2048      
 hNormalization)                                        

In [33]:
def compute_iou(boxes1, boxes2):
    boxes1_t = tf.stack([boxes1[..., 0] - boxes1[..., 2] / 2.0,
                         boxes1[..., 1] - boxes1[..., 3] / 2.0,
                         boxes1[..., 0] + boxes1[..., 2] / 2.0,
                         boxes1[..., 1] + boxes1[..., 3] / 2.0],
                         axis = -1)
                         
    boxes2_t = tf.stack([boxes2[..., 0] - boxes2[..., 2] / 2.0,
                         boxes2[..., 1] - boxes2[..., 3] / 2.0,
                         boxes2[..., 0] + boxes2[..., 2] / 2.0,
                         boxes2[..., 1] + boxes2[..., 3] / 2.0],
                         axis = -1)

    lu = tf.maximum(boxes1_t[..., :2], boxes2_t[..., :2])
    rd = tf.minimum(boxes1_t[..., 2:], boxes2_t[..., 2:])

    intersection = tf.maximum(0.0, rd - lu)
    inter_square = intersection[..., 0] * intersection[..., 1]

    square1 = boxes1[..., 2] * boxes1[..., 3]
    square2 = boxes2[..., 2] * boxes2[..., 3]

    union_square = tf.maximum(square1 + square2 - inter_square, 1e-10)

    return tf.clip_by_value(inter_square / union_square, 0.0, 1.0)

In [34]:
def difference(x, y):
    return tf.reduce_sum(tf.square(y - x))

In [35]:
def yolo_loss(y_true, y_pred):
    target = y_true[..., 0]

    y_pred_extract = tf.gather_nd(y_pred, tf.where(target[:] == 1))
    y_target_extract = tf.gather_nd(y_true, tf.where(target[:] == 1))

    rescaler = tf.where(target[:] == 1) * SPLIT_SIZE
    upscaler_1 = tf.concat([rescaler[:, 1:], tf.zeros([len(rescaler), 2], dtype=tf.int64)], axis=-1)

    target_upscaler_2 = tf.repeat([[float(SPLIT_SIZE), float(SPLIT_SIZE), 224., 224.]], repeats=[len(rescaler)], axis=0) * tf.cast(y_target_extract[..., 1:5], dtype=tf.float32)

    pred_1_upscaler_2 = tf.repeat([[float(SPLIT_SIZE), float(SPLIT_SIZE), 224., 224.]], repeats=[len(rescaler)], axis=0) * tf.cast(y_pred_extract[..., 1:5], dtype=tf.float32)

    pred_2_upscaler_2 = tf.repeat([[float(SPLIT_SIZE), float(SPLIT_SIZE), 224., 224.]], repeats=[len(rescaler)], axis=0) * tf.cast(y_pred_extract[..., 6:10], dtype=tf.float32)

    target_orig = tf.cast(upscaler_1, dtype=tf.float32) + target_upscaler_2
    pred_1_orig = tf.cast(upscaler_1, dtype=tf.float32) + pred_1_upscaler_2
    pred_2_orig = tf.cast(upscaler_1, dtype=tf.float32) + pred_2_upscaler_2


    mask = tf.cast(tf.math.greater(compute_iou(target_orig, pred_2_orig), compute_iou(target_orig, pred_1_orig)), dtype=tf.int32)

    y_pred_joined = tf.transpose(tf.concat([tf.expand_dims(y_pred_extract[..., 0], axis=0), tf.expand_dims(y_pred_extract[..., 5], axis=0)], axis=0))

    obj_pred = tf.gather_nd(y_pred_joined, tf.stack([tf.range(len(rescaler)), mask], axis=-1))

    object_loss = difference(tf.cast(obj_pred, dtype=tf.float32), tf.cast(tf.ones([len(rescaler)]), dtype=tf.float32))

    # Noobj

    y_pred_extract = tf.gather_nd(y_pred[..., 0:B*5], tf.where(target[:] == 0))

    y_target_extract = tf.zeros(len(y_pred_extract))

    no_object_loss_1 = difference(tf.cast(y_pred_extract[..., 0], dtype=tf.float32), tf.cast(y_target_extract, dtype=tf.float32))
    
    no_object_loss_2 = difference(tf.cast(y_pred_extract[..., 5], dtype=tf.float32), tf.cast(y_target_extract, dtype=tf.float32))
    
    no_object_loss = no_object_loss_1 + no_object_loss_2

    # Obj class loss

    y_pred_extract = tf.gather_nd(y_pred[..., 10:], tf.where(target[:] == 1))
    class_extract = tf.gather_nd(y_true[...,5:], tf.where(target[:] == 1))

    class_loss = difference(tf.cast(y_pred_extract, dtype=tf.float32), tf.cast(class_extract, dtype=tf.float32))

    # Obj bounding box loss

    y_pred_extract = tf.gather_nd(y_pred[..., 0:B*5], tf.where(target[:] == 1))
    centre_joined = tf.stack([y_pred_extract[..., 1:3], y_pred_extract[..., 6:8]], axis=1)
    centre_pred = tf.gather_nd(centre_joined, tf.stack([tf.range(len(rescaler)), mask], axis=-1))
    centre_target = tf.gather_nd(y_true[..., 1:3], tf.where(target[:] == 1))

    centre_loss = difference(centre_pred, centre_target)

    size_joined = tf.stack([y_pred_extract[..., 3:5], y_pred_extract[..., 8:10]], axis=1)

    size_pred = tf.gather_nd(size_joined, tf.stack([tf.range(len(rescaler)), mask], axis=-1))
    size_target = tf.gather_nd(y_true[..., 3:5], tf.where(target[:] == 1))

    size_loss = difference(tf.math.sqrt(tf.math.abs(size_pred)), tf.math.sqrt(tf.math.abs(size_target)))
    box_loss = centre_loss + size_loss

    lambda_coord = 5.0
    lambda_no_obj = 0.5

    loss = object_loss + (lambda_no_obj * no_object_loss) + tf.cast(lambda_coord * box_loss, dtype=tf.float32) + tf.cast(class_loss, dtype=tf.float32)
    
    return loss

In [36]:
# # y_true = generate_output([[0.210784, 0.616422, 0.127451, 0.232843, 2]])
# y_true = generate_output([[0.509804, 0.411765, 0.107843, 0.245098, 3],
#                           [0.210784, 0.616422, 0.127451, 0.232843, 2]])
# y_true = np.expand_dims(y_true, axis=0)
# y_pred = np.random.normal(size = (1, 7, 7, N_CLASSES+5*B))

# y_pred[0][1][4] = [0.9,0.47,0.31,0.12,0.23, 1.0,0.2,0.6,0.1,0.95, 0.9,0.8,0.2,0.6,0.1,0.5,0.9,0.35]
# y_pred[0][3][2] = [0.3,0.01,0.08,0.11,0.54, 0.98,0.56,0.88,0.1,0.24, 0.09,0.018,0.22,0.16,0.01,0.05,0.99,0.3]

# yolo_loss(y_true,y_pred)

In [37]:
# checkpoint_filepath = './yolo_resnet_50.h5'
checkpoint_filepath = './yolo_efficientnet_b1.h5'
callback = tf.keras.callbacks.ModelCheckpoint(
    filepath = checkpoint_filepath,
    save_weights_only = True,
    monitor = 'val_loss',
    mode = 'min',
    save_best_only = True
)

In [38]:
def scheduler(epoch, lr):
    if epoch < 40:
        return 1e-3
    elif epoch >= 40 and epoch < 80:
        return 5e-4
    else:
        return 1e-4

In [39]:
lr_callback = tf.keras.callbacks.LearningRateScheduler(scheduler)

In [40]:
model.compile(
    loss = yolo_loss,
    optimizer = Adam(1e-3)
)

In [ ]:
my_devices = tf.config.experimental.list_physical_devices(device_type='GPU')
tf.config.experimental.set_visible_devices(devices=my_devices, device_type='GPU')

In [ ]:
# 2h35 d'entrainement sur RTX 2080 et 60 epochs
history = model.fit(
    train_dataset,
    validation_data = val_dataset,
    verbose = 1,
    epochs = 60,
    callbacks = [lr_callback, callback]
)

## Testing

In [41]:
model.load_weights(checkpoint_filepath)

In [43]:
# COCO_PATH = './coco2017/val2017/' # A éviter si vous ne voulez pas que ça soit trop long
COCO_PATH = './VOC2012/ValJPEGImages/'

In [45]:
def model_test(filename):
    try:
        test_path = COCO_PATH + filename
        print(test_path)

        img = cv2.resize(cv2.imread(test_path), (H, W))

        image = tf.io.decode_jpeg(tf.io.read_file(test_path))
        image = tf.image.resize(image, [H, W])

        output = model.predict(np.expand_dims(image, axis=0))

        THRESH = .25

        object_positions = tf.concat([tf.where(output[..., 0] >= THRESH), tf.where(output[..., 5] >= THRESH)], axis=0)
        selected_output = tf.gather_nd(output, object_positions)
        final_boxes = []
        final_scores = []

        for i, pos in enumerate(object_positions):
            for j in range(2):
                if selected_output[i][j*5] > THRESH:
                    output_box = tf.cast(output[pos[0]][pos[1]][pos[2]][(j*5)+1:(j*5)+5], dtype=tf.float32)

                    x_centre = (tf.cast(pos[1], dtype=tf.float32) + output_box[0]) * 32
                    y_centre = (tf.cast(pos[2], dtype=tf.float32) + output_box[1]) * 32

                    x_width, y_height = tf.math.abs(H * output_box[2]), tf.math.abs(W * output_box[3])
                    x_min, y_min = int(x_centre - (x_width/2)), int(y_centre - (y_height/2))
                    x_max, y_max = int(x_centre + (x_width/2)), int(y_centre + (y_height/2))

                    if (x_min <= 0): x_min = 0
                    if (y_min <= 0): y_min = 0
                    if (x_max >= W): x_max = W
                    if (y_max >= H): y_max = H

                    final_boxes.append([x_min, y_min, x_max, y_max, str(classes[tf.argmax(selected_output[..., 10:], axis=-1)[i]])])
                    final_scores.append(selected_output[i][j*5])

        print(final_scores)
        print('final_boxes', final_boxes)
        final_boxes = np.array(final_boxes)

        object_classes = final_boxes[..., 4]
        nms_boxes = final_boxes[..., 0:4]

        nms_output = tf.image.non_max_suppression(nms_boxes, final_scores, max_output_size=100, iou_threshold=0.2, score_threshold=float('-inf'))
        print(nms_output)

        for i in nms_output:
            cv2.rectangle(
          img,
          (int(final_boxes[i][0]),int(final_boxes[i][1])),
          (int(final_boxes[i][2]),int(final_boxes[i][3])),(0,0,255),1)
            cv2.putText(
          img,
          final_boxes[i][-1],
          (int(final_boxes[i][0]),int(final_boxes[i][1])+15),
          cv2.FONT_HERSHEY_COMPLEX_SMALL,1,(2,225,155),1
          )
        print('--------------------------------')
        
        cv2.imwrite('./outputs/' + filename[:-4] + '_det' + '.jpg', cv2.resize(img, (256, 256)))

    except:
        print("No object found")

In [1]:
for filename in os.listdir(COCO_PATH):
    model_test(filename)